language: python
cache: pip

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 3.4
  - 2.7
  - pypy3
  - pypy

env:
  global:
    - TOXENV=py

matrix:
  include:
    - env: TOXENV=codestyle
    - env: TOXENV=docstyle

install: pip install tox

script: tox
